name: deploy
on:
  push:
    branches: [main]
    tags: [v*]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Image metadata
        id: meta_univ3
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
      - name: Image build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ steps.meta_services.outputs.tags }}
      - uses: cowprotocol/autodeploy-action@v1
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          pods: dfusion-v2-univ3
          tag: ${{ secrets.AUTODEPLOY_TAG }}
          url: ${{ secrets.AUTODEPLOY_URL }}
          token: ${{ secrets.AUTODEPLOY_TOKEN }}
